### PR TITLE
Added asset-copy task to include any images into the build folder

### PR DESCRIPTION
**Pull request by jadsalhani**
Why make my own when I can contribute to yours :)

I found it of need in a couple of my projects to I thought of proposing its addition
- Added asset-copy folder that includes the export of the task
- Just copies all files from app/assets to build/assets

If merged, it'll just need to be published by the team

### CODE REVIEW

**Comment by tlancina** [comment]
Thanks for the PR! Can I ask what the use case is for not having the assets in www already?

**Comment by jadsalhani** [comment]
Hi @tlancina 

Well from what I've seen (and done myself), the `www/build/` folder in itself is usually not committed with the project repository, so any images that would be added from on project member would not be transferred to the others.

Since the `serve:before` or `build:before` task deletes the `www/build` and then recompiles it, having the assets in a certain location would be beneficial so that they are copied on every build when the `www/build` folder gets reset

**Comment by jadsalhani** [comment]
Maybe committing the images would not be recommended, but at least have them stored in the `app/assets` folder to be present on each build of the application.

Since the `build` tasks deletes the `www/build/` folder, then the images pre-added would be deleted before being copied to the build

This task would solve that problem

**Comment by tlancina** [comment]
Is there any reason you can't have your assets in `www/assets/`?

**Comment by jadsalhani** [comment]
@tlancina  As far as I've encountered, the relative url that the files use is `build/...`, so having it outside of `build` folder would make it more difficult to use the assets

Might be a mistake from my side or something I missed, but that's the main reason

**Comment by tlancina** [comment]
Yep, but `build` and `assets` are siblings, so because the root is `www`, you can just do `assets/my-image.jpg` etc. Here's an example of static assets that are only in www: https://github.com/driftyco/ionic-conference-app/tree/master/www/data.

I don't disagree that there are some cases where you would want to manipulate images as part of your build, but I think for your case you can just leave them in `www`.

**Comment by jadsalhani** [comment]
Good point. I missed the fact that we can add to outside of `build/` folder and use the reference from there. I'll try to include the task as an option, that way it doesn't pollute the current build

**Pull request closed without merging**
